### ISSUE TITLE
KeyError: 'transactions'

### ISSUE THREAD

**Issue by alter42** [vBlackOut/vHackOS-Python#3]
Seems like a nice program, but i have an error that i can't figure out. 

50 HTTP/1.1" 200 None
2018-04-04 00:04:31 Alter-otthon root[25260] INFO {'result': '10'}
Traceback (most recent call last):
  File "main.py", line 22, in <module>
    main = run(ut)
  File "main.py", line 12, in __init__
    network = Network(ut)
  File "C:\python\vHackOSBot-Python-master\network.py", line 10, in __init__
    self.attackTarget(self.Configuration["attack_mode"])
  File "C:\python\vHackOSBot-Python-master\network.py", line 68, in attackTarget
    for info in yourbank["transactions"]:
KeyError: 'transactions'

Any ideas?

**Comment by vBlackOut** [comment]
fix please test my latest update
