### ISSUE TITLE
Closing Bot

### ISSUE THREAD

**Issue by Rayox** [vBlackOut/vHackOS-Python#5]
Bot is Closing upon Bad Request whats the problem here?

**Comment by Rayox** [comment]
Got the Error Log:
`Traceback (most recent call last):
  File "C:\Users\Takarien\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 386, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "C:\Users\Takarien\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 382, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\Takarien\AppData\Local\Programs\Python\Python36-32\lib\http\client.py", line 1331, in getresponse
    response.begin()
  File "C:\Users\Takarien\AppData\Local\Programs\Python\Python36-32\lib\http\client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "C:\Users\Takarien\AppData\Local\Programs\Python\Python36-32\lib\http\client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\Takarien\AppData\Local\Programs\Python\Python36-32\lib\socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\Takarien\AppData\Local\Programs\Python\Python36-32\lib\ssl.py", line 1009, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\Takarien\AppData\Local\Programs\Python\Python36-32\lib\ssl.py", line 871, in read
    return self._sslobj.read(len, buffer)
  File "C:\Users\Takarien\AppData\Local\Programs\Python\Python36-32\lib\ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Takarien\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\adapters.py", line 438, in send
    timeout=timeout
  File "C:\Users\Takarien\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 649, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Users\Takarien\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\packages\urllib3\util\retry.py", line 357, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\Takarien\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\packages\urllib3\packages\six.py", line 686, in reraise
    raise value
  File "C:\Users\Takarien\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "C:\Users\Takarien\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 388, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "C:\Users\Takarien\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 308, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
requests.packages.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.vhack.cc', port=443): Read timed out. (read timeout=5)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Takarien\Desktop\vHackOSBot-Python-master\main.py", line 27, in <module>
    main = run(ut)
  File "C:\Users\Takarien\Desktop\vHackOSBot-Python-master\main.py", line 16, in __init__
    network = Network(ut)
  File "C:\Users\Takarien\Desktop\vHackOSBot-Python-master\network.py", line 17, in __init__
    self.RecoltMoney()
  File "C:\Users\Takarien\Desktop\vHackOSBot-Python-master\network.py", line 119, in RecoltMoney
    self.ut.viewsPrint("showMsgCollectMoneyUser", "[{}] - \033[32m{} {} to '{}'\033[0m".format(os.path.basename(__file__), "\033[32myou are collected +", money, PlayerBruteIP))
  File "C:\Users\Takarien\Desktop\vHackOSBot-Python-master\utils.py", line 187, in viewsPrint
    return self.OutputTable("OutputBot: {} - {}".format(strftime("%Y-%m-%d %H:%M:%S", gmtime()), self.printConsole(Msg)), 2)
  File "C:\Users\Takarien\Desktop\vHackOSBot-Python-master\utils.py", line 215, in OutputTable
    self.account_info = self.requestStringNowait("update.php", accesstoken=self.Configuration["accessToken"])
  File "C:\Users\Takarien\Desktop\vHackOSBot-Python-master\utils.py", line 707, in requestStringNowait
    result = self.request.get(self.generateURL(self.uID, php, **kwargs), timeout=5)
  File "C:\Users\Takarien\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\sessions.py", line 531, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\Takarien\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\sessions.py", line 518, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Takarien\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\sessions.py", line 639, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Takarien\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\adapters.py", line 514, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.vhack.cc', port=443): Read timed out. (read timeout=5)
`

**Comment by ksga** [comment]
Same issue here.. Runs fine for a few minutes and then crashes. Seems to be some sort of IP-ban (connecting on my phone results in "no reply" unless switching to 4G).

**Comment by Rayox** [comment]
Found the cause its the vhsckos.cc api that timesout your ip due to too many requests.
